// @ts-check
/**
 * DelayPilot lint configuration.
 *
 * Owner: principal-architect. This file's job is to make the AGENTS.md §3.1 bans *mechanical*.
 * A ban that lives only in prose is a ban that ships broken in month three, so every construct
 * below that ESLint can express is expressed here rather than left to review.
 *
 * Not everything in §3.1 is lintable — "no mutable request state in module globals" and "no
 * hand-written binding interfaces" are review and CI concerns, not rule matches. Those stay in
 * the charters and in scripts/validate-build-system.mjs.
 */

import eslint from '@eslint/js'
import tseslint from 'typescript-eslint'
import astro from 'eslint-plugin-astro'
import prettier from 'eslint-config-prettier'
import globals from 'globals'

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.astro/**',
      '**/.wrangler/**',
      '**/worker-configuration.d.ts',
      'ml/**',
    ],
  },

  eslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    extends: [...tseslint.configs.strictTypeChecked, ...tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // AGENTS.md §3.1 — unbounded `any`.
      '@typescript-eslint/no-explicit-any': 'error',

      // AGENTS.md §3.1 — floating promises. A dropped promise in a Worker is a request that
      // silently does half its work.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // AGENTS.md §3.1 — `as unknown as` double casts. This is the escape hatch that turns every
      // other type guarantee into a suggestion.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSAsExpression > TSAsExpression > TSUnknownKeyword',
          message:
            'AGENTS.md §3.1 bans `as unknown as` double casts. Fix the type, add a runtime schema, or narrow properly.',
        },
        {
          selector: 'MemberExpression[object.name="Math"][property.name="random"]',
          message:
            'AGENTS.md §3.1 bans Math.random() for identifiers, tokens, and anything security-adjacent. Use crypto.randomUUID() or crypto.getRandomValues().',
        },
        {
          selector: 'TSInterfaceDeclaration[id.name="Env"]',
          message:
            'AGENTS.md §3.1 bans hand-written binding interfaces. `Env` is generated by `wrangler types` into worker-configuration.d.ts.',
        },
      ],

      // AGENTS.md §3.1 — passThroughOnException hides failures instead of surfacing them.
      'no-restricted-properties': [
        'error',
        {
          property: 'passThroughOnException',
          message:
            'AGENTS.md §3.1 bans passThroughOnException. Handle the error and return a designed state.',
        },
      ],

      // Unused code hides unfinished work. Underscore-prefixed args stay legal for interface
      // conformance.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // Config and script files run in Node and are not part of a tsconfig project.
  {
    files: ['**/*.{js,mjs,cjs}', 'scripts/**/*.mjs'],
    languageOptions: {
      globals: { ...globals.node },
    },
    extends: [tseslint.configs.disableTypeChecked],
  },

  ...astro.configs.recommended,

  prettier,
)
