/**
 * DelayPilot edge Worker.
 *
 * Owner: edge-api-engineer (DIRECTIVE.md Phase 7). This Phase 1 entry point establishes only the
 * router, the liveness probe, and the static-asset fallthrough — the shape every later route hangs
 * off. It deliberately implements no product behaviour.
 *
 * Request flow: `run_worker_first` in wrangler.jsonc routes only /api/*, /auth/*, /webhooks/* and
 * /go/* here. Everything else is served from the edge asset cache without invoking this Worker.
 * The ASSETS fallthrough below therefore handles only the residual case of an unmatched dynamic
 * path, not normal page traffic.
 */

import { Hono } from 'hono'

/**
 * `Env` is generated by `wrangler types` into worker-configuration.d.ts, which is owned by
 * platform-release-sre (docs/agents/ROSTER.md §3, shared-surface exception 2). AGENTS.md §3.1 bans
 * hand-written binding interfaces, so this file references the generated global and never declares
 * its own.
 */
const app = new Hono<{ Bindings: Env }>()

/**
 * DIRECTIVE.md §21: /health is liveness only. It asserts that this isolate is executing and
 * nothing more — no binding probes, no dependency checks, no configuration detail, no version of
 * any secret. Readiness (bindings, migrations, provider licence policy, in-force rule sets, Stripe
 * and email readiness) is a separate, production-protected endpoint owned by edge-api-engineer in
 * Phase 7.
 */
app.get('/api/v1/health', (c) =>
  c.json(
    {
      status: 'ok',
      service: 'delaypilot-edge',
      time: new Date().toISOString(),
    },
    200,
    { 'cache-control': 'no-store' },
  ),
)

/**
 * Unmatched dynamic paths get an RFC 9457 problem response rather than an HTML 404, so that an API
 * client never has to parse a page to discover that a route does not exist. The full problem-
 * response middleware — stable error codes, request ids, retryability, field errors — is Phase 7.
 */
app.all('/api/*', (c) =>
  c.json(
    {
      type: 'https://delaypilot.app/problems/not-found',
      title: 'Not Found',
      status: 404,
      detail: 'No such API route.',
    },
    404,
    { 'content-type': 'application/problem+json', 'cache-control': 'no-store' },
  ),
)

/**
 * Residual fallthrough to the pre-rendered apps/web build. `not_found_handling` is "none" in
 * wrangler.jsonc because apps/web has no 404 page yet, so an unmatched asset arrives here and
 * receives a plain 404 rather than a fabricated page.
 */
app.all('*', async (c) => {
  const response = await c.env.ASSETS.fetch(c.req.raw)
  return response.status === 404
    ? c.text('Not Found', 404, { 'cache-control': 'no-store' })
    : response
})

export default app
